# Generated by Django 4.2.5 on 2023-10-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(max_length=11)),
                ('nombre', models.CharField(max_length=3)),
                ('apellido', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('dependencia', models.CharField(max_length=20)),
                ('ciudad', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
