# Generated by Django 4.2.5 on 2023-10-02 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)]),
        ),
    ]
