# Generated by Django 4.2.5 on 2023-10-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tecnicos', '0001_initial'),
        ('clientes', '0002_alter_cliente_cedula'),
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='id_cliente',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='clientes.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='id_tecnico',
            field=models.ForeignKey(default=202, on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='Tecnicos.tecnico'),
            preserve_default=False,
        ),
    ]
